---
linters:
  enable:
  - revive

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      # Never check for logger errors.
      - (github.com/go-kit/log.Logger).Log
