go:
    # This must match .circle/config.yml.
    version: 1.21
repository:
    path: github.com/form3tech-oss/postgres_exporter
build:
    binaries:
        - name: postgres_exporter
          path: ./cmd/postgres_exporter
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
    platforms:
        - linux/amd64
        - linux/arm64
tarball:
    files:
        - LICENSE
        - NOTICE
