#!/bin/bash
# Concatenate a list of coverage reports
# Usage: concatenate_coverage <out> [[test] ...]

output_file=$1
shift
cat $1 > $output_file
shift

for f in $@ ; do
    tail -n +2 $f >> $output_file
done
