---
version: '3'
services:
  postgresql:
    image: ${POSTGRESQL_IMAGE:-postgres}
    container_name: postgres_exporter_postgresql
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  postgresql-ssl:
    image: ${POSTGRESQL_IMAGE:-postgres}
    container_name: postgres_exporter_postgresql-ssl
    command: >
      -c ssl=on
      -c ssl_cert_file=/ssl/server.crt
      -c ssl_key_file=/ssl/server.key
      -c log_min_messages=DEBUG4
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./testdata/ssl:/ssl
