name: Build and scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      VERSION: latest
      EXPORTER_NAME: postgresql-exporter
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Artifactory
        uses: docker/login-action@v1 
        with:
          registry: artifactory.internal.sysdig.com
          username: david.lorite@sysdig.com
          password: ${{ secrets.ARTI_TOKEN }}
      - name: Increase version and build
        run: |
          docker pull artifactory.internal.sysdig.com/$EXPORTER_NAME:$VERSION
          export RELEASE=$(docker inspect --format '{{ index .Config.Labels "release" }}' artifactory.internal.sysdig.com/$EXPORTER_NAME:$VERSION)
          docker build --label release=$RELEASE -f Dockerfile -t $EXPORTER_NAME:$VERSION --target scratch .
          docker build --label version=$RELEASE -f Dockerfile -t $EXPORTER_NAME:$VERSION-ubi --target ubi .  

      - name: Scan local image
        id: scan-local
        uses: sysdiglabs/scan-action@v3
        with:
          image-tag: "postgresql-exporter:latest"
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          ignore-failed-scan: true
          input-type: docker-daemon
          run-as-user: root
      - name: Scan local image 2
        id: scan-local2
        uses: sysdiglabs/scan-action@v3
        with:
          image-tag: "postgresql-exporter:latest-ubi"
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          ignore-failed-scan: true
          input-type: docker-daemon
          run-as-user: root

      - name: Sarif report
        uses: github/codeql-action/upload-sarif@v1  
        if: always()
        with:
          sarif_file: ${{ steps.scan-local.outputs.sarifReport }}

      - name: Change the tag of the image
        run: |
          docker tag $EXPORTER_NAME:$VERSION artifactory.internal.sysdig.com/$EXPORTER_NAME:$VERSION
          docker tag $EXPORTER_NAME:$VERSION-ubi artifactory.internal.sysdig.com/$EXPORTER_NAME:$VERSION-ubi

      - name: Push the image
        run: |
          docker push artifactory.internal.sysdig.com/$EXPORTER_NAME:$VERSION
          docker push artifactory.internal.sysdig.com/$EXPORTER_NAME:$VERSION-ubi